---
- hosts: all
  user: ec2-user
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
    - name: Copy script file and set permissions
      copy:
        src: ../filebeat.daemon.install.prd.sh
        dest: /tmp
        mode: 'a+x'

    - name: Run a script on remote hosts
      script: /tmp/filebeat.daemon.install.prd.sh
